create database python_db;
use python_db;
create table domains (domain_name varchar(255) NOT NULL, registrant_contact varchar(255), admin_contact varchar(255), tech_contact varchar(255), PRIMARY KEY (domain_name));
create table ips (ip_address varchar(255) NOT NULL, registrant_contact varchar(255), admin_contact varchar(255), tech_contact varchar(255), PRIMARY KEY (ip_address));
/*Password on server is more secure than local machine*/
create user 'python_user'@'localhost' identified by '1C@nn4ever';
create user 'python_user'@'localhost' identified by 'icann';
grant all privileges on python_db.* to 'python_user'@'localhost';
flush privileges;
insert into domains(domain_name, registrant_contact, admin_contact, tech_contact) values('test0.com', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into domains(domain_name, registrant_contact, admin_contact, tech_contact) values('test1.com', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into domains(domain_name, registrant_contact, admin_contact, tech_contact) values('test2.com', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into domains(domain_name, registrant_contact, admin_contact, tech_contact) values('test3.com', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into domains(domain_name, registrant_contact, admin_contact, tech_contact) values('test4.com', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into domains(domain_name, registrant_contact, admin_contact, tech_contact) values('test5.com', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into domains(domain_name, registrant_contact, admin_contact, tech_contact) values('test6.com', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into domains(domain_name, registrant_contact, admin_contact, tech_contact) values('test7.com', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into domains(domain_name, registrant_contact, admin_contact, tech_contact) values('test8.com', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into domains(domain_name, registrant_contact, admin_contact, tech_contact) values('test9.com', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');

insert into ips(ip_address, registrant_contact, admin_contact, tech_contact) values('10.0.0.0', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into ips(ip_address, registrant_contact, admin_contact, tech_contact) values('10.0.0.1', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into ips(ip_address, registrant_contact, admin_contact, tech_contact) values('10.0.0.2', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into ips(ip_address, registrant_contact, admin_contact, tech_contact) values('10.0.0.3', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into ips(ip_address, registrant_contact, admin_contact, tech_contact) values('10.0.0.4', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into ips(ip_address, registrant_contact, admin_contact, tech_contact) values('10.0.0.5', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into ips(ip_address, registrant_contact, admin_contact, tech_contact) values('10.0.0.6', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into ips(ip_address, registrant_contact, admin_contact, tech_contact) values('10.0.0.7', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into ips(ip_address, registrant_contact, admin_contact, tech_contact) values('10.0.0.8', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');
insert into ips(ip_address, registrant_contact, admin_contact, tech_contact) values('10.0.0.9', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org', 'matthew.ostovarpour@icann.org');